/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "inpwpkezefbdzgtcruoe"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlucHdwa2V6ZWZiZHpndGNydW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0Nzg3MjYsImV4cCI6MjA5MzA1NDcyNn0.RF-FiygYroeUS7XMpLzUViEPkPv_-6uQZKWXQYbEH7o"